apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wireguard
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: wireguard
    spec:
      containers:
        - env:
            - name: INTERNAL_SUBNET
              value: 10.13.13.0
            - name: PEERDNS
              value: auto
            - name: PEERS
              value: "2"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SERVERPORT
              value: "51820"
            - name: SERVERURL
              value: 192.168.178.60
            - name: TZ
              value: Europe/Berlin
          image: linuxserver/wireguard
          name: wireguard
          ports:
            - containerPort: 51820
              protocol: UDP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /config
              name: wireguard-claim0
            - mountPath: /lib/modules
              name: wireguard-claim1
      restartPolicy: Always
      volumes:
        - name: wireguard-claim0
          persistentVolumeClaim:
            claimName: wireguard-claim0
        - name: wireguard-claim1
          persistentVolumeClaim:
            claimName: wireguard-claim1
status: {}
