apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: wireguard
  name: wireguard
spec:
  ports:
    - name: "51820"
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    io.kompose.service: wireguard
status:
  loadBalancer: {}
